version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=FTaN2x5VVhIH7ts
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
api:
  container_name: workers-api
  build:
    context: ./
    #target: production
  image: workers-api
  depends_on:
    - db
  ports:
    - 8080:8080
  environment:
    NODE_ENV: production
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: postgres
    DB_PASSWORD: postgres
    # TODO: update to 'workers' when ready
    DB_NAME: postgres
  links:
    - db
  volumes:
    - './:/src'
volumes:
  db:
    driver: local
